export const FETCH_ALL_HABITS_OF_USER_REQUEST = 'FETCH_ALL_HABITS_OF_USER_REQUEST';
export const FETCH_ALL_HABITS_OF_USER_SUCCESS = 'FETCH_ALL_HABITS_OF_USER_SUCCESS';
export const FETCH_ALL_HABITS_OF_USER_FAIL = 'FETCH_ALL_HABITS_OF_USER_FAIL';

export const FETCH_SINGLE_HABIT_OF_USER_REQUEST = 'FETCH_SINGLE_HABIT_OF_USER_REQUEST';
export const FETCH_SINGLE_HABIT_OF_USER_SUCCESS = 'FETCH_SINGLE_HABIT_OF_USER_SUCCESS';
export const FETCH_SINGLE_HABIT_OF_USER_FAIL = 'FETCH_SINGLE_HABIT_OF_USER_FAIL';

export const HABIT_REQUEST = 'HABIT_REQUEST';
export const HABIT_REQUEST_SUCCESS = 'HABIT_REQUEST_SUCCESS';
export const HABIT_REQUEST_FAIL = 'HABIT_REQUEST_FAIL';
